### ISSUE TITLE
VRAM calculator doesn't work on some avatars

### ISSUE THREAD

**Issue by jangxx** [Thryrallo/VRC-Avatar-Performance-Tools#10]
For some reason, the VRAM calculator fails to correctly compute the Texture VRAM on some of my avatars while working flawlessly on others. Essentially, the tool just misses most of the textures and then arrives at a value far too low. Clicking on "Recalculate" or selecting a new avatar also logs an error into the console:

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Thry.AvatarHelpers.TextureVRAM.CalcSize (UnityEngine.Texture t, System.Boolean addToList) (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:428)
Thry.AvatarHelpers.TextureVRAM.Calc (UnityEngine.GameObject avatar) (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:349)
Thry.AvatarHelpers.TextureVRAM.OnGUI () (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:227)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)
```

Trying to use the Avatar Evaluator fails even worse, with ever movement of the mouse over the window logging similar errors and the "Recalculate" button not doing anything at all.

I'm running the latest version of the tool (Dec 3rd release) and have also re-imported the project and restarted Unity a couple of times with no effect.

**Comment by Thryrallo** [comment]
please retest with the newest version and post the stacktrace again if it occurs.

**Comment by Thryrallo** [comment]
Some bugs have been fixed since then, please test again.

**Comment by jangxx** [comment]
So I just tried this again with version 1.3.6 from VCC with Unity 2019 and the result is still the same,

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Thry.AvatarHelpers.TextureVRAM.TextureToBytesUsingBPP (UnityEngine.Texture t, System.Single bpp, System.Single resolutionScale) (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:1110)
Thry.AvatarHelpers.TextureVRAM.CalculateTextureSize (UnityEngine.Texture t, Thry.AvatarHelpers.TextureVRAM+TextureInfo info) (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:1085)
Thry.AvatarHelpers.TextureVRAM.Calc (UnityEngine.GameObject avatar) (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:885)
Thry.AvatarHelpers.TextureVRAM.OnGUI () (at Packages/de.thryrallo.vrc.avatar-performance-tools/Editor/VRAM Check/TextureVRAM.cs:538)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)
```

The Evaluator also fails in the same fashion as before.

**Comment by jangxx** [comment]
I dug a bit deeper (inserted `Debug.Log(rt.format.ToString() + ": " + (int)rt.format);` into the RenderTexture branch in `TextureToBytesUsingBPP`) and the problem seems to be that the avatar has a RenderTexture with an invalid format somehow. `rt.format` contains the value `29`, which is not any of the valid `RenderTextureFormat`s and on which `ToString` also doesn't work so I sadly can't tell you what the actual value is. The problem can easily be fixed however, by replacing the RenderTexture branch with this:

```c#
if (RT_BPP.ContainsKey(rt.format)) {
    double mipmaps = 1;
    for (int i = 0; i < rt.mipmapCount; i++) mipmaps += Math.Pow(0.25, i + 1);
    bytes = (long)((RT_BPP[rt.format] + rt.depth) * width * height * (rt.useMipMap ? mipmaps : 1) / 8);
} else {
    bytes = Profiler.GetRuntimeMemorySizeLong(t);
}
```

This not only fixes the problem, it also reveals which texture the culprit was:

![](https://i.imgur.com/0Pi2y1V.png)

The settings for it look like this:

![](https://i.imgur.com/NYJQGK5.png)

No idea what the problem is with these. Maybe you can figure it out.
